name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  kodi_api:
    path: ..
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
