targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/src/models/**.dart
            - lib/src/notifications/**.dart
            - lib/src/requests/**.dart
        options:
          explicit_to_json: true
          include_if_null: false
          field_rename: snake

      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/src/models/**.dart
            - lib/src/notifications/**.dart
            - lib/src/requests/**.dart
