import 'package:json_annotation/json_annotation.dart';

enum KodiPVRFieldsTimer {
  title,
  summary,
  @JsonValue('channelid')
  channelId,
  @JsonValue('isradio')
  isRadio,
  @JsonValue('istimerrule')
  isTimerRule,
  @JsonValue('ismanual')
  isManual,
  @JsonValue('starttime')
  startTime,
  @JsonValue('endtime')
  endTime,
  runtime,
  lifetime,
  @JsonValue('firstday')
  firstDay,
  weekdays,
  priority,
  @JsonValue('startmargin')
  startMargin,
  @JsonValue('endmargin')
  endMargin,
  state,
  file,
  directory,
  @JsonValue('preventduplicateepisodes')
  preventDuplicateEpisodes,
  @JsonValue('startanytime')
  startAnytime,
  @JsonValue('endanytime')
  endAnytime,
  @JsonValue('epgsearchstring')
  epgSearchString,
  @JsonValue('fulltextepgsearch')
  fullTextEpgSearch,
  @JsonValue('recordinggroup')
  recordingGroup,
  @JsonValue('maxrecordings')
  maxRecordings,
  @JsonValue('epguid')
  epgUID,
  @JsonValue('isreadonly')
  isReadOnly,
  @JsonValue('isreminder')
  isReminder,
  @JsonValue('clientid')
  clientId,
  @JsonValue('broadcastid')
  broadcastId,
}
