import 'package:json_annotation/json_annotation.dart';

enum KodiListFilterFieldsEpisodes {
  title,
  @JsonValue('tvshow')
  tvShow,
  @JsonValue('originaltitle')
  originalTitle,
  plot,
  votes,
  rating,
  @JsonValue('userrating')
  userRating,
  time,
  writers,
  @JsonValue('airdate')
  airDate,
  @JsonValue('playcount')
  playCount,
  @JsonValue('lastplayed')
  lastPlayed,
  @JsonValue('inprogress')
  inProgress,
  genre,
  year,
  director,
  actor,
  episode,
  season,
  filename,
  path,
  studio,
  @JsonValue('mpaarating')
  mpaaRating,
  @JsonValue('dateadded')
  dateAdded,
  tag,
  @JsonValue('videoresolution')
  videoResolution,
  @JsonValue('audiochannels')
  audioChannels,
  @JsonValue('audiocount')
  audioCount,
  @JsonValue('subtitlecount')
  subtitleCount,
  @JsonValue('videocodec')
  videoCodec,
  @JsonValue('audiocodec')
  audioCodec,
  @JsonValue('audiolanguage')
  audioLanguage,
  @JsonValue('subtitlelanguage')
  subtitleLanguage,
  @JsonValue('videoaspect')
  videoAspect,
  playlist,
  @JsonValue('virtualfolder')
  virtualFolder
}
