import 'package:json_annotation/json_annotation.dart';

enum KodiListFieldsAll {
  title,
  artist,
  @JsonValue('albumartist')
  albumArtist,
  genre,
  year,
  rating,
  album,
  track,
  duration,
  comment,
  lyrics,
  @JsonValue('musicbrainztrackid')
  musicBrainzTrackId,
  @JsonValue('musicbrainzartistid')
  musicBrainzArtistId,
  @JsonValue('musicbrainzalbumid')
  musicBrainzAlbumId,
  @JsonValue('musicbrainzalbumartistid')
  musicBrainzAlbumArtistId,
  @JsonValue('playcount')
  playCount,
  fanart,
  director,
  trailer,
  tagline,
  plot,
  @JsonValue('plotoutline')
  plotOutline,
  @JsonValue('originaltitle')
  originalTitle,
  @JsonValue('lastplayed')
  lastPlayed,
  writer,
  studio,
  mpaa,
  cast,
  country,
  @JsonValue('imdbnumber')
  imdbNumber,
  premiered,
  @JsonValue('productioncode')
  productionCode,
  runtime,
  set,
  @JsonValue('showlink')
  showLink,
  @JsonValue('streamdetails')
  streamDetails,
  top250,
  votes,
  @JsonValue('firstaired')
  firstAired,
  season,
  episode,
  @JsonValue('showtitle')
  showTitle,
  thumbnail,
  file,
  resume,
  @JsonValue('artistid')
  artistId,
  @JsonValue('albumid')
  albumId,
  @JsonValue('tvshowid')
  tvshowId,
  @JsonValue('setid')
  setId,
  @JsonValue('watchedepisodes')
  watchedEpisodes,
  disc,
  tag,
  art,
  @JsonValue('genreid')
  genreId,
  @JsonValue('displayartist')
  displayArtist,
  @JsonValue('albumartistid')
  albumArtistId,
  description,
  theme,
  mood,
  style,
  @JsonValue('albumlabel')
  albumLabel,
  @JsonValue('sorttitle')
  sortTitle,
  @JsonValue('episodeguide')
  episodeGuide,
  @JsonValue('uniqueid')
  uniqueId,
  @JsonValue('dateadded')
  dateAdded,
  channel,
  @JsonValue('channeltype')
  channelType,
  hidden,
  locked,
  @JsonValue('channelnumber')
  channelNumber,
  @JsonValue('subchannelnumber')
  subChannelNumber,
  @JsonValue('starttime')
  startTime,
  @JsonValue('endtime')
  endTime,
  @JsonValue('specialsortseason')
  specialSortSeason,
  @JsonValue('specialsortepisode')
  specialSortEpisode,
  compilation,
  @JsonValue('releasetype')
  releaseType,
  @JsonValue('albumreleasetype')
  albumReleaseType,
  contributors,
  @JsonValue('displaycomposer')
  displayComposer,
  @JsonValue('displayconductor')
  displayConductor,
  @JsonValue('displayorchestra')
  displayOrchestra,
  @JsonValue('displaylyricist')
  displayLyricist,
  @JsonValue('userrating')
  userRating,
  @JsonValue('sortartist')
  sortArtist,
  @JsonValue('musicbrainzreleasegroupid')
  musicBrainzReleaseGroupId,
  @JsonValue('mediapath')
  mediaPath,
  @JsonValue('dynpath')
  dynPath,
  @JsonValue('isboxset')
  isBoxSet,
  @JsonValue('totaldiscs')
  totalDiscs,
  @JsonValue('disctitle')
  disctTtle,
  @JsonValue('releasedate')
  releaseDate,
  @JsonValue('originaldate')
  originalDate,
  bpm,
  bitrate,
  @JsonValue('samplerate')
  sampleRate,
  channels,
  @JsonValue('albumstatus')
  albumStatus,
  @JsonValue('datemodified')
  dateModified,
  @JsonValue('datenew')
  dateNew,
  @JsonValue('customproperties')
  customProperties,
  @JsonValue('albumduration')
  albumDuration,
}
