import 'package:json_annotation/json_annotation.dart';

enum KodiListFilterFieldsMovies {
  title,
  @JsonValue('originaltitle')
  originalTitle,
  plot,
  @JsonValue('plotoutline')
  plotOutline,
  tagline,
  votes,
  rating,
  @JsonValue('userrating')
  userRating,
  time,
  writers,
  @JsonValue('playcount')
  playCount,
  @JsonValue('lastplayed')
  lastPlayed,
  @JsonValue('inprogress')
  inProgress,
  genre,
  country,
  year,
  director,
  actor,
  @JsonValue('mpaarating')
  mpaaRating,
  top250,
  studio,
  @JsonValue('hastrailer')
  hasTrailer,
  filename,
  path,
  set,
  tag,
  @JsonValue('dateadded')
  dateAdded,
  @JsonValue('videoresolution')
  videoResolution,
  @JsonValue('audiochannels')
  audioChannels,
  @JsonValue('audiocount')
  audioCount,
  @JsonValue('subtitlecount')
  subtitleCount,
  @JsonValue('videocodec')
  videoCodec,
  @JsonValue('audiocodec')
  audioCodec,
  @JsonValue('audiolanguage')
  audioLanguage,
  @JsonValue('subtitlelanguage')
  subtitleLanguage,
  @JsonValue('videoaspect')
  videoAspect,
  playlist,
  @JsonValue('virtualfolder')
  virtualFolder,
}
