// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'activate_window.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ActivateWindow _$$_ActivateWindowFromJson(Map<String, dynamic> json) =>
    _$_ActivateWindow(
      $enumDecode(_$KodiGUIWindowEnumMap, json['window']),
      (json['parameters'] as List<dynamic>).map((e) => e as String).toList(),
    );

Map<String, dynamic> _$$_ActivateWindowToJson(_$_ActivateWindow instance) =>
    <String, dynamic>{
      'window': _$KodiGUIWindowEnumMap[instance.window]!,
      'parameters': instance.parameters,
    };

const _$KodiGUIWindowEnumMap = {
  KodiGUIWindow.addon: 'addon',
  KodiGUIWindow.addonBrowser: 'addonbrowser',
  KodiGUIWindow.addonInformation: 'addoninformation',
  KodiGUIWindow.addonSettings: 'addonsettings',
  KodiGUIWindow.appearanceSettings: 'appearancesettings',
  KodiGUIWindow.busyDialog: 'busydialog',
  KodiGUIWindow.busyDialogNoCancel: 'busydialognocancel',
  KodiGUIWindow.contentSettings: 'contentsettings',
  KodiGUIWindow.contextMenu: 'contextmenu',
  KodiGUIWindow.eventLog: 'eventlog',
  KodiGUIWindow.extendedProgressDialog: 'extendedprogressdialog',
  KodiGUIWindow.favourites: 'favourites',
  KodiGUIWindow.fileBrowser: 'filebrowser',
  KodiGUIWindow.fileManager: 'filemanager',
  KodiGUIWindow.fullscreenGame: 'fullscreengame',
  KodiGUIWindow.fullscreenInfo: 'fullscreeninfo',
  KodiGUIWindow.fullscreenLiveTv: 'fullscreenlivetv',
  KodiGUIWindow.fullscreenLiveTvInput: 'fullscreenlivetvinput',
  KodiGUIWindow.fullscreenLiveTvPreview: 'fullscreenlivetvpreview',
  KodiGUIWindow.fullscreenRadio: 'fullscreenradio',
  KodiGUIWindow.fullscreenRadioInput: 'fullscreenradioinput',
  KodiGUIWindow.fullscreenRadioPreview: 'fullscreenradiopreview',
  KodiGUIWindow.fullscreenVideo: 'fullscreenvideo',
  KodiGUIWindow.gameAdvancedSettings: 'gameadvancedsettings',
  KodiGUIWindow.gameControllers: 'gamecontrollers',
  KodiGUIWindow.gameOSD: 'gameosd',
  KodiGUIWindow.gamepadInput: 'gamepadinput',
  KodiGUIWindow.games: 'games',
  KodiGUIWindow.gameSettings: 'gamesettings',
  KodiGUIWindow.gameStretchMode: 'gamestretchmode',
  KodiGUIWindow.gameVideoFilter: 'gamevideofilter',
  KodiGUIWindow.gameVideoRotation: 'gamevideorotation',
  KodiGUIWindow.gameVolume: 'gamevolume',
  KodiGUIWindow.home: 'home',
  KodiGUIWindow.infoProviderSettings: 'infoprovidersettings',
  KodiGUIWindow.interfaceSettings: 'interfacesettings',
  KodiGUIWindow.libExportSettings: 'libexportsettings',
  KodiGUIWindow.lockSettings: 'locksettings',
  KodiGUIWindow.loginScreen: 'loginscreen',
  KodiGUIWindow.mediaFilter: 'mediafilter',
  KodiGUIWindow.mediaSettings: 'mediasettings',
  KodiGUIWindow.mediaSource: 'mediasource',
  KodiGUIWindow.movieInformation: 'movieinformation',
  KodiGUIWindow.music: 'music',
  KodiGUIWindow.musicInformation: 'musicinformation',
  KodiGUIWindow.musicOSD: 'musicosd',
  KodiGUIWindow.musicPlaylist: 'musicplaylist',
  KodiGUIWindow.musicPlaylistEditor: 'musicplaylisteditor',
  KodiGUIWindow.networkSetup: 'networksetup',
  KodiGUIWindow.notification: 'notification',
  KodiGUIWindow.numericInput: 'numericinput',
  KodiGUIWindow.okDialog: 'okdialog',
  KodiGUIWindow.osdAudioSettings: 'osdaudiosettings',
  KodiGUIWindow.osdCMSSettings: 'osdcmssettings',
  KodiGUIWindow.osdSubtitleSettings: 'osdsubtitlesettings',
  KodiGUIWindow.osdVideoSettings: 'osdvideosettings',
  KodiGUIWindow.peripheralSettings: 'peripheralsettings',
  KodiGUIWindow.pictureInfo: 'pictureinfo',
  KodiGUIWindow.pictures: 'pictures',
  KodiGUIWindow.playerControls: 'playercontrols',
  KodiGUIWindow.playerProcessInfo: 'playerprocessinfo',
  KodiGUIWindow.playerSettings: 'playersettings',
  KodiGUIWindow.profiles: 'profiles',
  KodiGUIWindow.profileSettings: 'profilesettings',
  KodiGUIWindow.programs: 'programs',
  KodiGUIWindow.progressDialog: 'progressdialog',
  KodiGUIWindow.pvrChannelGuide: 'pvrchannelguide',
  KodiGUIWindow.pvrChannelManager: 'pvrchannelmanager',
  KodiGUIWindow.pvrChannelScan: 'pvrchannelscan',
  KodiGUIWindow.pvrGroupManager: 'pvrgroupmanager',
  KodiGUIWindow.pvrGuideControls: 'pvrguidecontrols',
  KodiGUIWindow.pvrGuideInfo: 'pvrguideinfo',
  KodiGUIWindow.pvrGuideSearch: 'pvrguidesearch',
  KodiGUIWindow.pvrOSDChannels: 'pvrosdchannels',
  KodiGUIWindow.pvrOSDGuide: 'pvrosdguide',
  KodiGUIWindow.pvrOSDTeleText: 'pvrosdteletext',
  KodiGUIWindow.pvrRadioRDSInfo: 'pvrradiordsinfo',
  KodiGUIWindow.pvrRecordingInfo: 'pvrrecordinginfo',
  KodiGUIWindow.pvrSettings: 'pvrsettings',
  KodiGUIWindow.pvrTimerSetting: 'pvrtimersetting',
  KodiGUIWindow.pvrUpdateProgress: 'pvrupdateprogress',
  KodiGUIWindow.radioChannels: 'radiochannels',
  KodiGUIWindow.radioGuide: 'radioguide',
  KodiGUIWindow.radioRecordings: 'radiorecordings',
  KodiGUIWindow.radioSearch: 'radiosearch',
  KodiGUIWindow.radioTimerRules: 'radiotimerrules',
  KodiGUIWindow.radioTimers: 'radiotimers',
  KodiGUIWindow.screenCalibration: 'screencalibration',
  KodiGUIWindow.screensaver: 'screensaver',
  KodiGUIWindow.seekBar: 'seekbar',
  KodiGUIWindow.selectDialog: 'selectdialog',
  KodiGUIWindow.serviceSettings: 'servicesettings',
  KodiGUIWindow.settings: 'settings',
  KodiGUIWindow.shutDownMenu: 'shutdownmenu',
  KodiGUIWindow.skinSettings: 'skinsettings',
  KodiGUIWindow.sliderDialog: 'sliderdialog',
  KodiGUIWindow.slideshow: 'slideshow',
  KodiGUIWindow.smartPlaylistEditor: 'smartplaylisteditor',
  KodiGUIWindow.smartPlaylistRule: 'smartplaylistrule',
  KodiGUIWindow.songInformation: 'songinformation',
  KodiGUIWindow.splash: 'splash',
  KodiGUIWindow.startup: 'startup',
  KodiGUIWindow.startWindow: 'startwindow',
  KodiGUIWindow.subMenu: 'submenu',
  KodiGUIWindow.subtitleSearch: 'subtitlesearch',
  KodiGUIWindow.systemInfo: 'systeminfo',
  KodiGUIWindow.systemSettings: 'systemsettings',
  KodiGUIWindow.teleText: 'teletext',
  KodiGUIWindow.textViewer: 'textviewer',
  KodiGUIWindow.tvChannels: 'tvchannels',
  KodiGUIWindow.tvGuide: 'tvguide',
  KodiGUIWindow.tvRecordings: 'tvrecordings',
  KodiGUIWindow.tvSearch: 'tvsearch',
  KodiGUIWindow.tvTimerRules: 'tvtimerrules',
  KodiGUIWindow.tvTimers: 'tvtimers',
  KodiGUIWindow.videoBookmarks: 'videobookmarks',
  KodiGUIWindow.videoMenu: 'videomenu',
  KodiGUIWindow.videoOSD: 'videoosd',
  KodiGUIWindow.videoPlaylist: 'videoplaylist',
  KodiGUIWindow.videos: 'videos',
  KodiGUIWindow.videoTimeSeek: 'videotimeseek',
  KodiGUIWindow.virtualKeyboard: 'virtualkeyboard',
  KodiGUIWindow.visualisation: 'visualisation',
  KodiGUIWindow.visualisationPresetList: 'visualisationpresetlist',
  KodiGUIWindow.volumeBar: 'volumebar',
  KodiGUIWindow.weather: 'weather',
  KodiGUIWindow.yesNoDialog: 'yesnodialog',
};
