import 'package:json_annotation/json_annotation.dart';

enum KodiGUIWindow {
  addon,
  @JsonValue('addonbrowser')
  addonBrowser,
  @JsonValue('addoninformation')
  addonInformation,
  @JsonValue('addonsettings')
  addonSettings,
  @JsonValue('appearancesettings')
  appearanceSettings,
  @JsonValue('busydialog')
  busyDialog,
  @JsonValue('busydialognocancel')
  busyDialogNoCancel,
  @JsonValue('contentsettings')
  contentSettings,
  @JsonValue('contextmenu')
  contextMenu,
  @JsonValue('eventlog')
  eventLog,
  @JsonValue('extendedprogressdialog')
  extendedProgressDialog,
  favourites,
  @JsonValue('filebrowser')
  fileBrowser,
  @JsonValue('filemanager')
  fileManager,
  @JsonValue('fullscreengame')
  fullscreenGame,
  @JsonValue('fullscreeninfo')
  fullscreenInfo,
  @JsonValue('fullscreenlivetv')
  fullscreenLiveTv,
  @JsonValue('fullscreenlivetvinput')
  fullscreenLiveTvInput,
  @JsonValue('fullscreenlivetvpreview')
  fullscreenLiveTvPreview,
  @JsonValue('fullscreenradio')
  fullscreenRadio,
  @JsonValue('fullscreenradioinput')
  fullscreenRadioInput,
  @JsonValue('fullscreenradiopreview')
  fullscreenRadioPreview,
  @JsonValue('fullscreenvideo')
  fullscreenVideo,
  @JsonValue('gameadvancedsettings')
  gameAdvancedSettings,
  @JsonValue('gamecontrollers')
  gameControllers,
  @JsonValue('gameosd')
  gameOSD,
  @JsonValue('gamepadinput')
  gamepadInput,
  games,
  @JsonValue('gamesettings')
  gameSettings,
  @JsonValue('gamestretchmode')
  gameStretchMode,
  @JsonValue('gamevideofilter')
  gameVideoFilter,
  @JsonValue('gamevideorotation')
  gameVideoRotation,
  @JsonValue('gamevolume')
  gameVolume,
  home,
  @JsonValue('infoprovidersettings')
  infoProviderSettings,
  @JsonValue('interfacesettings')
  interfaceSettings,
  @JsonValue('libexportsettings')
  libExportSettings,
  @JsonValue('locksettings')
  lockSettings,
  @JsonValue('loginscreen')
  loginScreen,
  @JsonValue('mediafilter')
  mediaFilter,
  @JsonValue('mediasettings')
  mediaSettings,
  @JsonValue('mediasource')
  mediaSource,
  @JsonValue('movieinformation')
  movieInformation,
  music,
  @JsonValue('musicinformation')
  musicInformation,
  @JsonValue('musicosd')
  musicOSD,
  @JsonValue('musicplaylist')
  musicPlaylist,
  @JsonValue('musicplaylisteditor')
  musicPlaylistEditor,
  @JsonValue('networksetup')
  networkSetup,
  notification,
  @JsonValue('numericinput')
  numericInput,
  @JsonValue('okdialog')
  okDialog,
  @JsonValue('osdaudiosettings')
  osdAudioSettings,
  @JsonValue('osdcmssettings')
  osdCMSSettings,
  @JsonValue('osdsubtitlesettings')
  osdSubtitleSettings,
  @JsonValue('osdvideosettings')
  osdVideoSettings,
  @JsonValue('peripheralsettings')
  peripheralSettings,
  @JsonValue('pictureinfo')
  pictureInfo,
  pictures,
  @JsonValue('playercontrols')
  playerControls,
  @JsonValue('playerprocessinfo')
  playerProcessInfo,
  @JsonValue('playersettings')
  playerSettings,
  profiles,
  @JsonValue('profilesettings')
  profileSettings,
  programs,
  @JsonValue('progressdialog')
  progressDialog,
  @JsonValue('pvrchannelguide')
  pvrChannelGuide,
  @JsonValue('pvrchannelmanager')
  pvrChannelManager,
  @JsonValue('pvrchannelscan')
  pvrChannelScan,
  @JsonValue('pvrgroupmanager')
  pvrGroupManager,
  @JsonValue('pvrguidecontrols')
  pvrGuideControls,
  @JsonValue('pvrguideinfo')
  pvrGuideInfo,
  @JsonValue('pvrguidesearch')
  pvrGuideSearch,
  @JsonValue('pvrosdchannels')
  pvrOSDChannels,
  @JsonValue('pvrosdguide')
  pvrOSDGuide,
  @JsonValue('pvrosdteletext')
  pvrOSDTeleText,
  @JsonValue('pvrradiordsinfo')
  pvrRadioRDSInfo,
  @JsonValue('pvrrecordinginfo')
  pvrRecordingInfo,
  @JsonValue('pvrsettings')
  pvrSettings,
  @JsonValue('pvrtimersetting')
  pvrTimerSetting,
  @JsonValue('pvrupdateprogress')
  pvrUpdateProgress,
  @JsonValue('radiochannels')
  radioChannels,
  @JsonValue('radioguide')
  radioGuide,
  @JsonValue('radiorecordings')
  radioRecordings,
  @JsonValue('radiosearch')
  radioSearch,
  @JsonValue('radiotimerrules')
  radioTimerRules,
  @JsonValue('radiotimers')
  radioTimers,
  @JsonValue('screencalibration')
  screenCalibration,
  screensaver,
  @JsonValue('seekbar')
  seekBar,
  @JsonValue('selectdialog')
  selectDialog,
  @JsonValue('servicesettings')
  serviceSettings,
  settings,
  @JsonValue('shutdownmenu')
  shutDownMenu,
  @JsonValue('skinsettings')
  skinSettings,
  @JsonValue('sliderdialog')
  sliderDialog,
  slideshow,
  @JsonValue('smartplaylisteditor')
  smartPlaylistEditor,
  @JsonValue('smartplaylistrule')
  smartPlaylistRule,
  @JsonValue('songinformation')
  songInformation,
  splash,
  startup,
  @JsonValue('startwindow')
  startWindow,
  @JsonValue('submenu')
  subMenu,
  @JsonValue('subtitlesearch')
  subtitleSearch,
  @JsonValue('systeminfo')
  systemInfo,
  @JsonValue('systemsettings')
  systemSettings,
  @JsonValue('teletext')
  teleText,
  @JsonValue('textviewer')
  textViewer,
  @JsonValue('tvchannels')
  tvChannels,
  @JsonValue('tvguide')
  tvGuide,
  @JsonValue('tvrecordings')
  tvRecordings,
  @JsonValue('tvsearch')
  tvSearch,
  @JsonValue('tvtimerrules')
  tvTimerRules,
  @JsonValue('tvtimers')
  tvTimers,
  @JsonValue('videobookmarks')
  videoBookmarks,
  @JsonValue('videomenu')
  videoMenu,
  @JsonValue('videoosd')
  videoOSD,
  @JsonValue('videoplaylist')
  videoPlaylist,
  videos,
  @JsonValue('videotimeseek')
  videoTimeSeek,
  @JsonValue('virtualkeyboard')
  virtualKeyboard,
  visualisation,
  @JsonValue('visualisationpresetlist')
  visualisationPresetList,
  @JsonValue('volumebar')
  volumeBar,
  weather,
  @JsonValue('yesnodialog')
  yesNoDialog,
}
