import 'package:json_annotation/json_annotation.dart';

enum KodiInputAction {
  @JsonValue('analogfastforward')
  analogFastForward,
  @JsonValue('analogmove')
  analogMove,
  @JsonValue('analogmovexleft')
  analogMoveXLeft,
  @JsonValue('analogmovexright')
  analogMoveXRight,
  @JsonValue('analogmoveydown')
  analogMoveYDown,
  @JsonValue('analogmoveyup')
  analogMoveYUp,
  @JsonValue('analogrewind')
  analogRewind,
  @JsonValue('analogseekback')
  analogSeekBack,
  @JsonValue('analogseekforward')
  analogSeekForward,
  @JsonValue('aspectratio')
  aspectRatio,
  @JsonValue('audiodelay')
  audioDelay,
  @JsonValue('audiodelayminus')
  audioDelayMinus,
  @JsonValue('audiodelayplus')
  audioDelayPlus,
  @JsonValue('audionextlanguage')
  audioNextLanguage,
  @JsonValue('audiotoggledigital')
  audioToggleDigital,
  back,
  backspace,
  @JsonValue('bigstepback')
  bigStepBack,
  @JsonValue('bigstepforward')
  bigStepForward,
  blue,
  @JsonValue('browsesubtitle')
  browseSubtitle,
  @JsonValue('channeldown')
  channelDown,
  @JsonValue('channelnumberseparator')
  channelNumberSeparator,
  @JsonValue('channelup')
  channelUp,
  @JsonValue('chapterorbigstepback')
  chapterOrBigStepBack,
  @JsonValue('chapterorbigstepforward')
  chapterOrBigStepForward,
  close,
  @JsonValue('codecinfo')
  codecInfo,
  @JsonValue('contextmenu')
  contextMenu,
  copy,
  @JsonValue('createbookmark')
  createBookmark,
  @JsonValue('createepisodebookmark')
  createRpisodeBookmark,
  @JsonValue('cursorleft')
  cursorLeft,
  @JsonValue('cursorright')
  cursorRight,
  @JsonValue('cyclesubtitle')
  cycleSubtitle,
  @JsonValue('cycletonemapmethod')
  cycleToneMapMethod,
  @JsonValue('decreasepar')
  decreasePar,
  @JsonValue('decreaserating')
  decreaseRating,
  @JsonValue('decreasevisrating')
  decreaseVisRating,
  delete,
  @JsonValue('doubleclick')
  doubleClick,
  down,
  enter,
  error,
  @JsonValue('fastforward')
  fastForward,
  filter,
  @JsonValue('filterclear')
  filterClear,
  @JsonValue('filtersms2')
  filterSMS2,
  @JsonValue('filtersms3')
  filterSMS3,
  @JsonValue('filtersms4')
  filterSMS4,
  @JsonValue('filtersms5')
  filterSMS5,
  @JsonValue('filtersms6')
  filterSMS6,
  @JsonValue('filtersms7')
  filterSMS7,
  @JsonValue('filtersms8')
  filterSMS8,
  @JsonValue('filtersms9')
  filterSMS9,
  @JsonValue('firstpage')
  firstPage,
  fullscreen,
  green,
  @JsonValue('guiprofile')
  guiProfile,
  @JsonValue('hdrtoggle')
  hdrToggle,
  highlight,
  @JsonValue('increasepar')
  increasePar,
  @JsonValue('increaserating')
  increaseRating,
  @JsonValue('increasevisrating')
  increaseVisRating,
  info,
  @JsonValue('jumpsms2')
  jumpSMS2,
  @JsonValue('jumpsms3')
  jumpSMS3,
  @JsonValue('jumpsms4')
  jumpSMS4,
  @JsonValue('jumpsms5')
  jumpSMS5,
  @JsonValue('jumpsms6')
  jumpSMS6,
  @JsonValue('jumpsms7')
  jumpSMS7,
  @JsonValue('jumpsms8')
  jumpSMS8,
  @JsonValue('jumpsms9')
  jumpSMS9,
  @JsonValue('lastpage')
  lastPage,
  left,
  @JsonValue('leftclick')
  leftClick,
  @JsonValue('lockpreset')
  lockPreset,
  @JsonValue('longclick')
  longClick,
  @JsonValue('longpress')
  longPress,
  menu,
  @JsonValue('middleclick')
  middleClick,
  @JsonValue('mousedrag')
  mouseDrag,
  @JsonValue('mousedragend')
  mouseDragEnd,
  @JsonValue('mousemove')
  mouseMove,
  move,
  @JsonValue('moveitemdown')
  moveItemDown,
  @JsonValue('moveitemup')
  moveItemUp,
  mute,
  @JsonValue('nextcalibration')
  nextCalibration,
  @JsonValue('nextchannelgroup')
  nextChannelGroup,
  @JsonValue('nextletter')
  nextLetter,
  @JsonValue('nextpicture')
  nextPicture,
  @JsonValue('nextpreset')
  nextPreset,
  @JsonValue('nextresolution')
  nextResolution,
  @JsonValue('nextscene')
  nextScene,
  @JsonValue('nextstereomode')
  nextStereoMode,
  @JsonValue('nextsubtitle')
  nextSubtitle,
  noop,
  number0,
  number1,
  number2,
  number3,
  number4,
  number5,
  number6,
  number7,
  number8,
  number9,
  osd,
  @JsonValue('pagedown')
  pageDown,
  @JsonValue('pageup')
  pageUp,
  @JsonValue('pangesture')
  panGesture,
  @JsonValue('parentdir')
  parentDir,
  @JsonValue('parentfolder')
  parentFolder,
  pause,
  play,
  @JsonValue('playerdebug')
  playerDebug,
  @JsonValue('playerdebugvideo')
  playerDebugBideo,
  @JsonValue('playerprocessinfo')
  playerProcessInfo,
  @JsonValue('playerprogramselect')
  playerProgramSelect,
  @JsonValue('playerresolutionselect')
  playerResolutionSelect,
  playlist,
  @JsonValue('playnext')
  playNext,
  @JsonValue('playpause')
  playPause,
  @JsonValue('playpvr')
  playPVR,
  @JsonValue('playpvrradio')
  playPVRRadio,
  @JsonValue('playpvrtv')
  playPVRTv,
  @JsonValue('previouschannelgroup')
  previousChannelGroup,
  @JsonValue('previousmenu')
  previousMenu,
  @JsonValue('previouspicture')
  previousPicture,
  @JsonValue('previouspreset')
  previousPreset,
  @JsonValue('previousscene')
  previousScene,
  @JsonValue('previousstereomode')
  previousStereoMode,
  @JsonValue('prevletter')
  prevLetter,
  queue,
  @JsonValue('randompreset')
  randomPreset,
  record,
  red,
  @JsonValue('reloadkeymaps')
  reloadKeymaps,
  rename,
  @JsonValue('resetcalibration')
  resetCalibration,
  rewind,
  right,
  @JsonValue('rightclick')
  rightClick,
  rotate,
  @JsonValue('rotateccw')
  rotateCCW,
  @JsonValue('rotategesture')
  rotateGesture,
  @JsonValue('scanitem')
  scanItem,
  screenshot,
  @JsonValue('scrolldown')
  scrollDown,
  @JsonValue('scrollup')
  scrollUp,
  select,
  @JsonValue('setrating')
  setRating,
  @JsonValue('settingslevelchange')
  settingsLevelChange,
  @JsonValue('settingsreset')
  settingsReset,
  shift,
  @JsonValue('showpreset')
  showPreset,
  @JsonValue('showsubtitles')
  showSubtitles,
  @JsonValue('showtime')
  showTime,
  @JsonValue('showtimerrule')
  showTimerRule,
  @JsonValue('showvideomenu')
  showVideoMenu,
  @JsonValue('skipnext')
  skipNext,
  @JsonValue('skipprevious')
  skipPrevious,
  @JsonValue('smallstepback')
  smallStepBack,
  @JsonValue('stepback')
  stepBack,
  @JsonValue('stepforward')
  stepForward,
  @JsonValue('stereomode')
  stereoMode,
  @JsonValue('stereomodetomono')
  stereoModeToMono,
  stop,
  @JsonValue('subtitlealign')
  subtitleAlign,
  @JsonValue('subtitledelay')
  subtitleDelay,
  @JsonValue('subtitledelayminus')
  subtitleDelayMinus,
  @JsonValue('subtitledelayplus')
  subtitledDelayPlus,
  @JsonValue('subtitleshiftdown')
  subtitleShiftDown,
  @JsonValue('subtitleshiftup')
  subtitleShiftUp,
  @JsonValue('swipedown')
  swipeDown,
  @JsonValue('swipeleft')
  swipeLeft,
  @JsonValue('swiperight')
  swipeRight,
  @JsonValue('swipeup')
  swipeUp,
  @JsonValue('switchplayer')
  switchPlayer,
  symbols,
  tap,
  @JsonValue('togglecommskip')
  toggleCommSkip,
  @JsonValue('togglefont')
  toggleFont,
  @JsonValue('togglefullscreen')
  toggleFullscreen,
  @JsonValue('togglestereomode')
  toggleStereoMode,
  @JsonValue('togglewatched')
  toggleWatched,
  up,
  @JsonValue('verticalshiftdown')
  verticalShiftDown,
  @JsonValue('verticalshiftup')
  verticalShiftUp,
  @JsonValue('videonextstream')
  videoNextStream,
  @JsonValue('voicerecognizer')
  voiceRecognizer,
  @JsonValue('volampdown')
  volAmpDown,
  @JsonValue('volampup')
  volAmpUp,
  @JsonValue('volumeamplification')
  volumeAmplification,
  @JsonValue('volumedown')
  volumeDown,
  @JsonValue('volumeup')
  volumeUp,
  @JsonValue('wheeldown')
  wheelDown,
  @JsonValue('wheelup')
  wheelUp,
  yellow,
  @JsonValue('zoomgesture')
  zoomgesture,
  @JsonValue('zoomin')
  zoomin,
  @JsonValue('zoomlevel1')
  zoomLevel1,
  @JsonValue('zoomlevel2')
  zoomLevel2,
  @JsonValue('zoomlevel3')
  zoomLevel3,
  @JsonValue('zoomlevel4')
  zoomLevel4,
  @JsonValue('zoomlevel5')
  zoomLevel5,
  @JsonValue('zoomlevel6')
  zoomLevel6,
  @JsonValue('zoomlevel7')
  zoomLevel7,
  @JsonValue('zoomlevel8')
  zoomLevel8,
  @JsonValue('zoomlevel9')
  zoomLevel9,
  @JsonValue('zoomnormal')
  zoomNormal,
  @JsonValue('zoomout')
  zoomOut,
}
