import 'package:json_annotation/json_annotation.dart';

enum KodiVideoFieldsEpisode {
  title,
  plot,
  votes,
  rating,
  writer,
  @JsonValue('firstaired')
  firstAired,
  @JsonValue('playcount')
  playCount,
  runtime,
  director,
  @JsonValue('productioncode')
  productionCode,
  season,
  episode,
  @JsonValue('originaltitle')
  originalTitle,
  @JsonValue('showtitle')
  showTitle,
  cast,
  @JsonValue('streamdetails')
  streamDetails,
  @JsonValue('lastplayed')
  lastPlayed,
  fanart,
  thumbnail,
  file,
  resume,
  @JsonValue('tvshowid')
  tvShowId,
  @JsonValue('dateadded')
  dateAdded,
  @JsonValue('uniqueid')
  uniqueId,
  art,
  @JsonValue('specialsortseason')
  specialSortSeason,
  @JsonValue('specialsortepisode')
  specialSortEpisode,
  @JsonValue('userrating')
  userRating,
  @JsonValue('seasonid')
  seasonId,
  ratings,
}
