import 'package:json_annotation/json_annotation.dart';

enum KodiVideoFieldsMovie {
  title,
  genre,
  year,
  rating,
  director,
  trailer,
  tagline,
  plot,
  @JsonValue('plotoutline')
  plotOutline,
  @JsonValue('originaltitle')
  originalTitle,
  @JsonValue('lastplayed')
  lastPlayed,
  @JsonValue('playcount')
  playCount,
  writer,
  studio,
  mpaa,
  cast,
  country,
  @JsonValue('imdbnumber')
  imdbNumber,
  runtime,
  set,
  @JsonValue('showlink')
  showLink,
  @JsonValue('streamdetails')
  streamDetails,
  top250,
  votes,
  fanart,
  thumbnail,
  file,
  @JsonValue('sorttitle')
  sortTitle,
  resume,
  @JsonValue('setid')
  setId,
  @JsonValue('dateadded')
  dateAdded,
  tag,
  art,
  @JsonValue('userrating')
  userRating,
  ratings,
  premiered,
  @JsonValue('uniqueid')
  uniqueId,
}
