import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kodi_api/src/requests/kodi_request.dart';
import 'package:kodi_api/src/requests/kodi_response.dart';

part 'button_event.freezed.dart';
part 'button_event.g.dart';

typedef ButtonEventBuilder = ButtonEvent Function(
  String button,
  KodiInputKeymapType keymap, {
  @Default(0) int holdTime,
});

@freezed
class ButtonEvent with _$ButtonEvent implements KodiRequest<void> {
  @Assert('holdTime >= 0')
  const factory ButtonEvent(
    String button,
    KodiInputKeymapType keymap, {
    @JsonKey(name: 'holdtime') @Default(0) int holdTime,
  }) = _ButtonEvent;

  const ButtonEvent._();

  factory ButtonEvent.fromJson(Map<String, dynamic> json) =>
      _$ButtonEventFromJson(json);

  @override
  String get method => 'Input.ButtonEvent';

  @override
  void handleResponse(KodiResponseSuccess response) {}
}

enum KodiKBButton {
  backspace,
  tab,
  returnn,
  escape,
  esc,
  zero,
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  a,
  b,
  c,
  d,
  e,
  f,
  g,
  h,
  i,
  j,
  k,
  l,
  m,
  n,
  o,
  p,
  q,
  r,
  s,
  t,
  u,
  v,
  w,
  x,
  y,
  z,
  space,
  exclaim,
  doubleQuote,
  hash,
  dollar,
  percent,
  ampersand,
  quote,
  @JsonValue('leftbracket')
  leftBracket,
  @JsonValue('rightbracket')
  rightBracket,
  asterisk,
  plus,
  comma,
  minus,
  period,
  @JsonValue('forwardslash')
  forwardSlash,
  colon,
  semicolon,
  @JsonValue('lessthan')
  lessThan,
  equals,
  @JsonValue('greaterthan')
  greaterThan,
  @JsonValue('questionmark')
  questionMark,
  at,
  @JsonValue('opensquarebracket')
  openSquareBracket,
  backslash,
  @JsonValue('closesquarebracket')
  closeSquareBracket,
  caret,
  underline,
  @JsonValue('leftquote')
  leftQuote,
  @JsonValue('openbrace')
  openBrace,
  pipe,
  @JsonValue('closebrace')
  closeBrace,
  tilde,
  @JsonValue('numpadzero')
  numpadZero,
  @JsonValue('numpadone')
  numpaDone,
  @JsonValue('numpadtwo')
  numpadTwo,
  @JsonValue('numpadthree')
  numpadThree,
  @JsonValue('numpadfour')
  numpadFour,
  @JsonValue('numpadfive')
  numpadFive,
  @JsonValue('numpadsix')
  numpadSix,
  @JsonValue('numpadseven')
  numpadSeven,
  @JsonValue('numpadeight')
  numpadEight,
  @JsonValue('numpadnine')
  numpadNine,
  @JsonValue('numpaddivide')
  numpadDivide,
  @JsonValue('numpadtimes')
  numpadTimes,
  @JsonValue('numpadminus')
  numpadMinus,
  @JsonValue('numpadplus')
  numpadPlus,
  enter,
  @JsonValue('numpadperiod')
  numpadPeriod,
  @JsonValue('browserback')
  browserBack,
  @JsonValue('browserforward')
  browserForward,
  @JsonValue('browserrefresh')
  browserRefresh,
  @JsonValue('browserstop')
  browserStop,
  @JsonValue('browsersearch')
  browserSearch,
  @JsonValue('browserfavorites')
  browserFavorites,
  @JsonValue('browserhome')
  browserHome,
  @JsonValue('volumemute')
  volumeMute,
  @JsonValue('volumedown')
  volumeDown,
  @JsonValue('volumeup')
  volumeUp,
  @JsonValue('nexttrack')
  nextTrack,
  @JsonValue('prevtrack')
  prevTrack,
  stop,
  @JsonValue('playpause')
  playPause,
  rewind,
  @JsonValue('fastforward')
  fastForward,
  @JsonValue('launchmail')
  launchMail,
  @JsonValue('launchmediaselect')
  launchMediaSelect,
  @JsonValue('launchapp1pcicon')
  launchApp1PcIcon,
  @JsonValue('launchapp2pcicon')
  launchApp2PcIcon,
  @JsonValue('launchfilebrowser')
  launchFileBrowser,
  @JsonValue('launchmediacenter')
  launchMediaCenter,
  record,
  f1,
  f2,
  f3,
  f4,
  f5,
  f6,
  f7,
  f8,
  f9,
  f10,
  f11,
  f12,
  f13,
  f14,
  f15,
  up,
  down,
  right,
  left,
  insert,
  delete,
  home,
  end,
  @JsonValue('pageup')
  pageUp,
  @JsonValue('pagedown')
  pageDown,
  numlock,
  capslock,
  @JsonValue('rightshift')
  rightShift,
  @JsonValue('leftshift')
  leftShift,
  @JsonValue('rightctrl')
  rightCtrl,
  @JsonValue('leftctrl')
  leftCtrl,
  @JsonValue('leftalt')
  leftAlt,
  @JsonValue('leftwindows')
  leftWindows,
  @JsonValue('rightwindows')
  rightWindows,
  menu,
  pause,
  @JsonValue('scrolllock')
  scrollLock,
  @JsonValue('printscreen')
  printScreen,
  power,
  sleep,
  guide,
  settings,
  info,
  red,
  green,
  yellow,
  blue,
  zoom,
  text,
  favorites,
  homepage,
  config,
  epg,
}

enum KodiXGButton {
  a,
  b,
  x,
  y,
  white,
  black,
  start,
  back,
  @JsonValue('leftthumbbutton')
  leftThumbButton,
  @JsonValue('rightthumbbutton')
  rightThumbButton,
  @JsonValue('leftthumbstick')
  leftThumbStick,
  @JsonValue('leftthumbstickup')
  leftThumbStickUp,
  @JsonValue('leftthumbstickdown')
  leftThumbStickDown,
  @JsonValue('leftthumbstickleft')
  leftThumbStickLeft,
  @JsonValue('leftthumbstickright')
  leftThumbStickRight,
  @JsonValue('rightthumbstick')
  rightThumbStick,
  @JsonValue('rightthumbstickup')
  rightThumbStickUp,
  @JsonValue('rightthumbstickdown')
  rightThumbStickDown,
  @JsonValue('rightthumbstickleft')
  rightThumbStickLeft,
  @JsonValue('rightthumbstickright')
  rightThumbStickRight,
  @JsonValue('lefttrigger')
  leftTrigger,
  @JsonValue('righttrigger')
  rightTrigger,
  @JsonValue('leftanalogtrigger')
  leftAnalogTrigger,
  @JsonValue('rightanalogtrigger')
  rightAnalogTrigger,
  @JsonValue('dpadleft')
  dpadLeft,
  @JsonValue('dpadright')
  dpadRight,
  @JsonValue('dpadup')
  dpadUp,
  @JsonValue('dpaddown')
  dpadDown,
}

enum KodiR1Button {
  left,
  right,
  up,
  down,
  select,
  back,
  menu,
  info,
  display,
  title,
  play,
  pause,
  reverse,
  forward,
  @JsonValue('skipplus')
  skipPlus,
  @JsonValue('skipminus')
  skipMinus,
  stop,
  zero,
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  power,
  @JsonValue('mytv')
  myTv,
  @JsonValue('mymusic')
  myMusic,
  @JsonValue('mypictures')
  myPictures,
  @JsonValue('myvideo')
  myVideo,
  record,
  start,
  @JsonValue('volumeplus')
  volumePlus,
  @JsonValue('volumeminus')
  volumeMinus,
  @JsonValue('channelplus')
  channelPlus,
  @JsonValue('channelminus')
  channelMinus,
  @JsonValue('pageplus')
  pagePlus,
  @JsonValue('pageminus')
  pageMinus,
  @JsonValue('mute')
  mute,
  @JsonValue('recordedtv')
  recordedTv,
  guide,
  @JsonValue('livetv')
  liveTv,
  @JsonValue('liveradio')
  liveRadio,
  @JsonValue('epgsearch')
  epgSearch,
  star,
  hash,
  clear,
  enter,
  xbox,
  playlist,
  teletext,
  red,
  green,
  yellow,
  blue,
  subtitle,
  language,
  eject,
  @JsonValue('contentsmenu')
  contentsMenu,
  @JsonValue('rootmenu')
  rootMenu,
  @JsonValue('topmenu')
  topMenu,
  @JsonValue('dvdmenu')
  dvdMenu,
  print,
}

enum KodiR2Button {
  fakeEnum,
}

enum KodiInputKeymapType {
  @JsonValue('KB')
  kb,
  @JsonValue('XG')
  xg,
  @JsonValue('R1')
  r1,
  @JsonValue('R2')
  r2,
}
