import 'package:json_annotation/json_annotation.dart';

enum KodiAudioFieldsSong {
  title,
  artist,
  @JsonValue('albumartist')
  albumArtist,
  genre,
  year,
  rating,
  album,
  track,
  duration,
  comment,
  lyrics,
  @JsonValue('musicbrainztrackid')
  musicBrainzTrackId,
  @JsonValue('musicbrainzartistid')
  musicBrainzArtistId,
  @JsonValue('musicbrainzalbumid')
  musicBrainzAlbumId,
  @JsonValue('musicbrainzalbumartistid')
  musicBrainzAlbumArtistId,
  @JsonValue('playcount')
  playCount,
  fanart,
  thumbnail,
  file,
  @JsonValue('albumid')
  albumId,
  @JsonValue('lastplayed')
  lastPlayed,
  disc,
  @JsonValue('genreid')
  genreId,
  @JsonValue('artistid')
  artistId,
  @JsonValue('displayartist')
  displayArtist,
  @JsonValue('albumartistid')
  albumArtistId,
  @JsonValue('albumreleasetype')
  albumReleaseType,
  @JsonValue('dateadded')
  dateAdded,
  votes,
  @JsonValue('userrating')
  userRating,
  mood,
  contributors,
  @JsonValue('displaycomposer')
  displayComposer,
  @JsonValue('displayconductor')
  displayConductor,
  @JsonValue('displayorchestra')
  displayOrchestra,
  @JsonValue('displaylyricist')
  displayLyricist,
  @JsonValue('sortartist')
  sortArtist,
  art,
  @JsonValue('sourceid')
  sourceId,
  @JsonValue('disctitle')
  discTitle,
  @JsonValue('releasedate')
  releaseDate,
  @JsonValue('originaldate')
  originalDate,
  bpm,
  @JsonValue('samplerate')
  sampleRate,
  bitrate,
  channels,
  @JsonValue('datemodified')
  dateModified,
  @JsonValue('datenew')
  dateNew,
}
