import 'package:json_annotation/json_annotation.dart';

enum KodiAudioFieldsAlbum {
  title,
  description,
  artist,
  genre,
  theme,
  mood,
  style,
  type,
  @JsonValue('albumlabel')
  albumLabel,
  rating,
  votes,
  @JsonValue('userrating')
  userRating,
  year,
  @JsonValue('musicbrainzalbumid')
  musicBrainzAlbumId,
  @JsonValue('musicbrainzalbumartistid')
  musicBrainzAlbumArtistId,
  fanart,
  thumbnail,
  @JsonValue('playcount')
  playCount,
  @JsonValue('artistid')
  artistId,
  @JsonValue('displayartist')
  displayArtist,
  compilation,
  @JsonValue('releasetype')
  releaseType,
  @JsonValue('dateadded')
  dateAdded,
  @JsonValue('sortartist')
  sortArtist,
  @JsonValue('musicbrainzreleasegroupid')
  musicBrainzReleaseGroupId,
  @JsonValue('songgenres')
  songGenres,
  art,
  @JsonValue('lastplayed')
  lastPlayed,
  @JsonValue('sourceid')
  sourceId,
  @JsonValue('isboxset')
  isBoxSet,
  @JsonValue('totaldiscs')
  totalDiscs,
  @JsonValue('releasedate')
  releaseDate,
  @JsonValue('originaldate')
  originalDate,
  @JsonValue('albumstatus')
  albumStatus,
  @JsonValue('datemodified')
  dateModified,
  @JsonValue('datenew')
  dateNew,
  @JsonValue('albumduration')
  albumDuration,
}
